
CREATE TABLE `prodi` (
  `id` int(11) NOT NULL auto_increment,
  `fakultas` varchar(100) NOT NULL,
  `prodi` VARCHAR(100) NOT NULL,
  `program` varchar(100) NOT NULL,
  `akreditasi` varchar(100) NOT NULL,
  PRIMARY KEY  (`id`)
);

INSERT INTO `prodi` (`id`, `fakultas`, `prodi`, `program`, `akreditasi`) VALUES
(1	,'FEB'	,'Akuntansi'	,'D3'	,'A'),
(2	,'FEB'	,'Keuangan dan Perbankan'	,'D3'	,'A'),
(3	,'FEB'	,'Manajemen Pemasaran'	,'D3'	,'A'),
(4	,'FEB'	,'Perpajakan'	,'D3'	,'A'),
(5	,'FISIP'	,'Administrasi Perkantoran'	,'D3'	,'B'),
(6	,'FISIP'	,'Hubungan Masyarakat'	,'D3'	,'B'),
(7	,'FISIP'	,'Perpustakaan'	,'D3'	,'A'),
(8	,'FMIPA'	,'Manajemen Informatika'	,'D3'	,'B'),
(9	,'FP'	,'Perkebunan'	,'D3'	,'B'),
(10	,'FT'	,'Teknik Mesin'	,'D3'	,'B'),
(11	,'FT'	,'Teknik Sipil'	,'D3'	,'B'),
(12	,'FT'	,'Teknik Survey dan Pemetaan'	,'D3'	,'B'),
(13	,'FK'	,'Dokter'	,'Profesi'	,'A'),
(14	,'FKIP'	,'Pendidikan Profesi Guru'	,'Profesi'	,'Baik'),
(15	,'FT'	,'Insinyur'	,'Profesi'	,'C'),
(16	,'FEB'	,'Akuntansi'	,'S1'	,'A'),
(17	,'FEB'	,'Ekonomi Pembangunan'	,'S1'	,'A'),
(18	,'FEB'	,'Manajemen'	,'S1'	,'A'),
(19	,'FH'	,'Ilmu Hukum'	,'S1'	,'A'),
(20	,'FISIP'	,'Hubungan Internasional'	,'S1'	,'B'),
(21	,'FISIP'	,'Ilmu Administrasi Bisnis'	,'S1'	,'A'),
(22	,'FISIP'	,'Ilmu Administrasi Negara'	,'S1'	,'A'),
(23	,'FISIP'	,'Ilmu Komunikasi'	,'S1'	,'A'),
(24	,'FISIP'	,'Ilmu Pemerintahan'	,'S1'	,'B'),
(25	,'FISIP'	,'Sosiologi'	,'S1'	,'A'),
(26	,'FK'	,'Farmasi'	,'S1'	,'Sedang Proses'),
(27	,'FK'	,'Pendidikan Dokter'	,'S1'	,'A'),
(28	,'FKIP'	,'Bimbingan dan Konseling'	,'S1'	,'B'),
(29	,'FKIP'	,'Pendidikan Bahasa dan Sastra Indonesia'	,'S1'	,'A'),
(30	,'FKIP'	,'Pendidikan Bahasa Inggris'	,'S1'	,'B'),
(31	,'FKIP'	,'Pendidikan Bahasa Lampung'	,'S1'	,'Sedang Proses'),
(32	,'FKIP'	,'Pendidikan Bahasa Perancis'	,'S1'	,'B'),
(33	,'FKIP'	,'Pendidikan Biologi'	,'S1'	,'B'),
(34	,'FKIP'	,'Pendidikan Ekonomi'	,'S1'	,'B'),
(35	,'FKIP'	,'Pendidikan Fisika'	,'S1'	,'A'),
(36	,'FKIP'	,'Pendidikan Geografi'	,'S1'	,'A'),
(37	,'FKIP'	,'Pendidikan Guru Pendidikan Anak Usia Dini'	,'S1'	,'B'),
(38	,'FKIP'	,'Pendidikan Guru Sekolah Dasar'	,'S1'	,'A'),
(39	,'FKIP'	,'Pendidikan Jasmani'	,'S1'	,'B'),
(40	,'FKIP'	,'Pendidikan Kimia'	,'S1'	,'B'),
(41	,'FKIP'	,'Pendidikan Matematika'	,'S1'	,'B'),
(42	,'FKIP'	,'Pendidikan Musik'	,'S1'	,'Baik'),
(43	,'FKIP'	,'Pendidikan Pancasila dan Kewarganegaraan'	,'S1'	,'B'),
(44	,'FKIP'	,'Pendidikan Sejarah'	,'S1'	,'B'),
(45	,'FKIP'	,'Pendidikan Tari'	,'S1'	,'B'),
(46	,'FKIP'	,'Pendidikan Teknologi Informasi'	,'S1'	,'Baik'),
(47	,'FMIPA'	,'Biologi'	,'S1'	,'A'),
(48	,'FMIPA'	,'Fisika'	,'S1'	,'A'),
(49	,'FMIPA'	,'Ilmu Komputer'	,'S1'	,'A'),
(50	,'FMIPA'	,'Kimia'	,'S1'	,'A'),
(51	,'FMIPA'	,'Matematika'	,'S1'	,'B'),
(52	,'FP'	,'Agribisnis'	,'S1'	,'A'),
(53	,'FP'	,'Agronomi'	,'S1'	,'B'),
(54	,'FP'	,'Agroteknologi'	,'S1'	,'A'),
(55	,'FP'	,'Budidaya Perairan'	,'S1'	,'A'),
(56	,'FP'	,'Ilmu Kelautan'	,'S1'	,'B'),
(57	,'FP'	,'Ilmu Tanah'	,'S1'	,'B'),
(58	,'FP'	,'Kehutanan'	,'S1'	,'A'),
(59	,'FP'	,'Nutrisi dan Teknologi Pakan Ternak'	,'S1'	,'Baik'),
(60	,'FP'	,'Penyuluhan Pertanian'	,'S1'	,'B'),
(61	,'FP'	,'Peternakan'	,'S1'	,'B'),
(62	,'FP'	,'Proteksi Tanaman'	,'S1'	,'B'),
(63	,'FP'	,'Sumber Daya Akuatik'	,'S1'	,'B'),
(64	,'FP'	,'Teknik Pertanian'	,'S1'	,'A'),
(65	,'FP'	,'Teknologi Hasil Pertanian'	,'S1'	,'A'),
(66	,'FP'	,'Teknologi Industri Pertanian'	,'S1'	,'B'),
(67	,'FT'	,'Arsitektur'	,'S1'	,'B'),
(68	,'FT'	,'Teknik Elektro'	,'S1'	,'A'),
(69	,'FT'	,'Teknik Geodesi'	,'S1'	,'B'),
(70	,'FT'	,'Teknik Geofisika'	,'S1'	,'A'),
(71	,'FT'	,'Teknik Informatika'	,'S1'	,'B'),
(72	,'FT'	,'Teknik Kimia'	,'S1'	,'B'),
(73	,'FT'	,'Teknik Mesin'	,'S1'	,'B'),
(74	,'FT'	,'Teknik Sipil'	,'S1'	,'A'),
(75	,'FMIPA'	,'Biologi Terapan'	,'S1'	,'Baik'),
(76	,'FT'	,'Teknik Lingkungan'	,'S1'	,'Sedang Proses'),
(77	,'FEB'	,'Ilmu Akuntansi'	,'S2'	,'UNGGUL'),
(78	,'FEB'	,'Ilmu Ekonomi'	,'S2'	,'A'),
(79	,'FEB'	,'Manajemen'	,'S2'	,'A'),
(80	,'FH'	,'Ilmu Hukum'	,'S2'	,'A'),
(81	,'FISIP'	,'Ilmu Administrasi'	,'S2'	,'B'),
(82	,'FISIP'	,'Ilmu Komunikasi'	,'S2'	,'B'),
(83	,'FISIP'	,'Ilmu Pemerintahan'	,'S2'	,'B'),
(84	,'FK'	,'Kesehatan Masyarakat'	,'S2'	,'Baik'),
(85	,'FKIP'	,'Administrasi Pendidikan'	,'S2'	,'B'),
(86	,'FKIP'	,'Keguruan Guru SD'	,'S2'	,'B'),
(87	,'FKIP'	,'Pendidikan Ilmu Pengetahuan Alam'	,'S2'	,'B'),
(88	,'FKIP'	,'Pendidikan Bahasa dan Kebudayaan Lampung'	,'S2'	,'B'),
(89	,'FKIP'	,'Pendidikan Bahasa dan Sastra Indonesia'	,'S2'	,'B'),
(90	,'FKIP'	,'Pendidikan Bahasa Inggris'	,'S2'	,'Baik Sekali'),
(91	,'FKIP'	,'Pendidikan Fisika'	,'S2'	,'B'),
(92	,'FKIP'	,'Pendidikan Ilmu Pengetahuan Sosial'	,'S2'	,'B'),
(93	,'FKIP'	,'Pendidikan Matematika'	,'S2'	,'B'),
(94	,'FKIP'	,'Teknologi Pendidikan'	,'S2'	,'B'),
(95	,'FMIPA'	,'Biologi'	,'S2'	,'B'),
(96	,'FMIPA'	,'Fisika'	,'S2'	,'B'),
(97	,'FMIPA'	,'Kimia'	,'S2'	,'B'),
(98	,'FMIPA'	,'Matematika'	,'S2'	,'B'),
(99	,'FP'	,'Agribisnis'	,'S2'	,'A'),
(100	,'FP'	,'Agronomi'	,'S2'	,'A'),
(101	,'FP'	,'Ilmu Kehutanan'	,'S2'	,'B'),
(102	,'FP'	,'Penyuluhan dan Komunikasi Pertanian'	,'S2'	,'B'),
(103	,'FP'	,'Teknologi Industri Pertanian'	,'S2'	,'A'),
(104	,'FT'	,'Teknik Elektro'	,'S2'	,'B'),
(105	,'FT'	,'Teknik Mesin'	,'S2'	,'B'),
(106	,'FT'	,'Teknik Sipil'	,'S2'	,'B'),
(107	,'PASCA'	,'Ilmu Lingkungan'	,'S2'	,'B'),
(108	,'PASCA'	,'Ilmu Penyuluhan Pembangunan'	,'S2'	,'C'),
(109	,'PASCA'	,'Manajemen Wilayah Pesisir dan Laut'	,'S2'	,'B'),
(110	,'PASCA'	,'Perencanaan Wilayah dan Kota'	,'S2'	,'Baik'),
(111	,'FEB'	,'Ilmu Ekonomi'	,'S3'	,'B'),
(112	,'FH'	,'Ilmu Hukum'	,'S3'	,'Baik Sekali'),
(113	,'FISIP'	,'Pembangunan'	,'S3'	,'Sedang Proses'),
(114	,'FKIP'	,'Pendidikan'	,'S3'	,'Sedang Proses'),
(115	,'FMIPA'	,'Matematika dan Ilmu Pengetahuan Alam'	,'S3'	,'Baik Sekali'),
(116	,'FP'	,'Ilmu Pertanian'	,'S3'	,'B'),
(117	,'PASCA'	,'Ilmu Lingkungan'	,'S3'	,'Baik'),
(118	,'FK'	,'Pulmonologi dan Ilmu Kedokteran Respirasi'	,'Spesialis 1'	,'Sedang Proses');